const board=document.querySelector('#board'),rotateButton=document.querySelector('#rotate'),piecePreview=document.querySelector('#piece-preview'),placedCount=document.querySelector('#placed-count'),totalCount=document.querySelector('#total-count'),undoButton=document.querySelector('#undo'),winPanel=document.querySelector('#win');
const shapes=[[[0,0],[1,0],[0,1]],[[0,0],[1,0],[1,1]],[[1,0],[0,1],[1,1]],[[0,0],[0,1],[1,1]]];
let size=8,blocked=0,rotation=0,nextTileId=1,cells=[],placements=[];
const indexOf=(x,y)=>y*size+x;
function newPuzzle(nextSize=size){size=nextSize;rotation=0;nextTileId=1;placements=[];blocked=Math.floor(Math.random()*size*size);renderBoard();updateUI();winPanel.hidden=true;}
function renderBoard(){board.innerHTML='';board.style.gridTemplateColumns=`repeat(${size},1fr)`;board.setAttribute('aria-rowcount',size);board.setAttribute('aria-colcount',size);cells=Array.from({length:size*size},(_,index)=>{const cell=document.createElement('button'),x=index%size,y=Math.floor(index/size);cell.type='button';cell.className=index===blocked?'cell blocked':'cell';cell.dataset.index=index;cell.setAttribute('role','gridcell');cell.setAttribute('aria-label',index===blocked?`Missing square, row ${y+1}, column ${x+1}`:`Row ${y+1}, column ${x+1}`);cell.addEventListener('mouseenter',()=>previewAt(x,y));cell.addEventListener('mouseleave',clearPreview);cell.addEventListener('focus',()=>previewAt(x,y));cell.addEventListener('blur',clearPreview);cell.addEventListener('click',()=>handleCell(index,x,y));board.appendChild(cell);return cell;});}
const candidateAt=(x,y)=>shapes[rotation].map(([dx,dy])=>indexOf(x+dx,y+dy));
function isValid(candidate,x,y){if(x<0||y<0||x+1>=size||y+1>=size)return false;return candidate.every(index=>index!==blocked&&!cells[index]?.dataset.tile);}
function previewAt(x,y){clearPreview();const candidate=candidateAt(x,y),valid=isValid(candidate,x,y);candidate.forEach(index=>{if(cells[index])cells[index].classList.add(valid?'preview':'invalid');});}
function clearPreview(){cells.forEach(cell=>cell.classList.remove('preview','invalid'));}
function handleCell(index,x,y){const existing=Number(cells[index].dataset.tile||0);if(existing){removeTile(existing);return;}const candidate=candidateAt(x,y);if(!isValid(candidate,x,y))return;const id=nextTileId++,color=placements.length%4;candidate.forEach(cellIndex=>{cells[cellIndex].dataset.tile=id;cells[cellIndex].classList.add('filled',`tile-${color}`);});placements.push({id,cells:candidate,color});clearPreview();updateUI();if(placements.length===(size*size-1)/3)winPanel.hidden=false;}
function removeTile(id){const placement=placements.find(item=>item.id===id);if(!placement)return;placement.cells.forEach(index=>{delete cells[index].dataset.tile;cells[index].classList.remove('filled',`tile-${placement.color}`);});placements=placements.filter(item=>item.id!==id);updateUI();}
function undo(){const last=placements.at(-1);if(last)removeTile(last.id);}
function reset(){placements.forEach(placement=>placement.cells.forEach(index=>{delete cells[index].dataset.tile;cells[index].classList.remove('filled',`tile-${placement.color}`);}));placements=[];nextTileId=1;winPanel.hidden=true;updateUI();}
function rotate(){rotation=(rotation+1)%4;piecePreview.style.transform=`rotate(${rotation*90}deg)`;}
function updateUI(){placedCount.textContent=placements.length;totalCount.textContent=(size*size-1)/3;undoButton.disabled=placements.length===0;document.querySelectorAll('[data-size]').forEach(button=>button.classList.toggle('active',Number(button.dataset.size)===size));piecePreview.style.transform=`rotate(${rotation*90}deg)`;}
document.querySelectorAll('[data-size]').forEach(button=>button.addEventListener('click',()=>newPuzzle(Number(button.dataset.size))));rotateButton.addEventListener('click',rotate);undoButton.addEventListener('click',undo);document.querySelector('#reset').addEventListener('click',reset);document.querySelector('#new-puzzle-top').addEventListener('click',()=>newPuzzle());document.querySelector('#play-again').addEventListener('click',()=>newPuzzle());document.addEventListener('keydown',event=>{if(event.key.toLowerCase()==='r'&&!event.metaKey&&!event.ctrlKey)rotate();if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='z')undo();});piecePreview.appendChild(document.createElement('span'));newPuzzle();
